[package]
name = "docxtplrs"
version = "0.1.0"
edition = "2021"

[lib]
name = "docxtplrs"
crate-type = ["cdylib", "rlib"]

[features]
default = []
extension-module = ["pyo3/extension-module"]

[dependencies]
pyo3 = "0.29"
minijinja = { version = "2", features = ["loader", "unicode"] }
zip = { version = "2", default-features = false, features = ["deflate"] }
fancy-regex = "0.14"
quick-xml = "0.36"
crc32fast = "1"
sha1 = "0.10"
encoding_rs = "0.8"
